baseURL: "/"
languageCode: en-us
title: "Learning from language"
theme: "ath-tufte-hugo_archivo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: https://github.com/glupyan/learning_from_language/blob/master/content/learning_from_language_syllabus.pdf
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
#    - name: Resources
#      url: /resources/
#      weight: 3
    - name: Final Paper
      url: /finalpaper/
      weight: 3
params:
  subtitle: ""
  author: Gary Lupyan
  thumbnail: /noun_Graph_963326.png
  instructor: 
    name:  Prof. Gary Lupyan
    email: lupyan@wisc.edu
    url: "http://sapir.psych.wisc.edu"
    signup: "<b> [meeting signup](https://calendly.com/glupyan/psych711)</b>"
    office: "<b> Brogden 419</b>"
    oh: "By Appt. Sign up below"
  course:
    number: Psych 711
    semester: Spring 2022
    days: "Thursdsays"
    time: "9:00am-11:30am"
    location1: "Brogden 634"
    dates: "January - May 2022"
    copyrightYear: "2022"
    contactDetails: >-

  university: 
    name: University of Wisconsin-Madison
    url: "https://www.cmu.edu"
  school:
    name: Department of Psychology
    url: ""
  description: ""
  primaryColor: "#E50000"
  secondaryColor: "#D08770"
  credits: ""
  logo:
    url: /images/noun_Graph_963326.png
    alt: Learning from Language
  meta:
    twitterSite: ""
    twitterCreator: ""
    fbAuthor: ""
